// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-03bPhRqexvad4O6MscXgET7pw_Ao1tQ',
    appId: '1:907713567786:web:3302c81e72eab0535cf753',
    messagingSenderId: '907713567786',
    projectId: 'jnfoislocaltest',
    authDomain: 'jnfoislocaltest.firebaseapp.com',
    databaseURL: 'https://jnfoislocaltest-default-rtdb.firebaseio.com',
    storageBucket: 'jnfoislocaltest.firebasestorage.app',
    measurementId: 'G-8JRN8DN5ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFNbQLdCEXJq780P8YSFit3_fMhhYs04',
    appId: '1:907713567786:android:79765db874d31d5f5cf753',
    messagingSenderId: '907713567786',
    projectId: 'jnfoislocaltest',
    databaseURL: 'https://jnfoislocaltest-default-rtdb.firebaseio.com',
    storageBucket: 'jnfoislocaltest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJrWXd7glwCyQ3DpUOYD-zdQO1TgFX78',
    appId: '1:907713567786:ios:bbc996200bec28135cf753',
    messagingSenderId: '907713567786',
    projectId: 'jnfoislocaltest',
    databaseURL: 'https://jnfoislocaltest-default-rtdb.firebaseio.com',
    storageBucket: 'jnfoislocaltest.firebasestorage.app',
    iosBundleId: 'com.example.groveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJrWXd7glwCyQ3DpUOYD-zdQO1TgFX78',
    appId: '1:907713567786:ios:bbc996200bec28135cf753',
    messagingSenderId: '907713567786',
    projectId: 'jnfoislocaltest',
    databaseURL: 'https://jnfoislocaltest-default-rtdb.firebaseio.com',
    storageBucket: 'jnfoislocaltest.firebasestorage.app',
    iosBundleId: 'com.example.groveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-03bPhRqexvad4O6MscXgET7pw_Ao1tQ',
    appId: '1:907713567786:web:4fdc1a8fd200354a5cf753',
    messagingSenderId: '907713567786',
    projectId: 'jnfoislocaltest',
    authDomain: 'jnfoislocaltest.firebaseapp.com',
    databaseURL: 'https://jnfoislocaltest-default-rtdb.firebaseio.com',
    storageBucket: 'jnfoislocaltest.firebasestorage.app',
    measurementId: 'G-1GRJZ709EX',
  );
}
